id: P003057
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W2PD17468
  title: གུ་རུའི་རྟོགས་བརྗོད་པ་ངོ་མཚར་རྒྱ་མཚོའི་འཇིངས་རྣམ།
  author: ''
  volumes:
    22e463be4ba54504b09b0d669cc64744:
      image_group_id: I4PD723
      title: ''
      volume_number: 1
      total_pages: 550
      base_file: v001.txt
